spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://120.79.253.92/wxsell?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
    port: 8090



wechat:
  mpAppId: wxcd63bfe698a536a5
  mpAppSecret: 735f99e57f397d14bbaeb00d898d0816
  mchId: 1502262451
  mchKey: ci5d7dk430322ddfcvpew334dferce58
  keyPath: D:/zzh/cert/apiclient_cert.p12
  notifyUrl: http://wxsell.nat200.top/sell/pay/notify
  templateId:
    orderStatus: yOQdE1n9KgkSIqH6di2M8np772JRrNXMyXGDRZnFFp0
    paid: lNOaJWubiKA_XU5xE0U5X4WFsUHEzVYSz4eM0AF7gC8

projectUrl:
  wechatMpAuthorize: http://wxsell.nat200.top
  wechatOpenAuthorize: http://wxsell.nat200.top
  sell: http://wxsell.nat200.top

